version: '3.7'
services:
  janus:
    build:
      context: ./janus-9
      dockerfile: Dockerfile
    image: tms/janus:0.9.1
    container_name: tms-janus_0.9.1
    # network_mode: 'host'
    # ports:
    #   - '8088:8088'
    #   - '10000-10099:10000-10099/udp'
    volumes:
      #   - /usr/local/etc/ssl:/usr/local/etc/ssl
      - ./tms-plugins:/usr/src/janus-plugins
    env_file:
      - ./sample.env

  ue_play:
    build:
      context: ./ue_play
      args:
        vue_app_title: tms-janus 播放器
        vue_app_base_url: player
        # vue_app_janus_address:
        # vue_app_janus_hostname: janus
        # vue_app_janus_http_port: 8088
        # vue_app_janus_https_port: 8089
    image: tms-janus/ue-player:latest
    container_name: tms-janus-ue_play
    # ports:
    #   - '8080:80'
    #   - '443:443'
    # volumes:
    #   - /usr/local/etc/ssl:/usr/local/etc/ssl
    environment:
      - NGINX_WEB_BASE_URL=/play
    env_file:
      - ./sample.env

  ue_demo:
    build: ./ue_demo
    image: tms-janus/ue_demo
    container_name: tms-janus-ue_demo
    # ports:
    #   - '8081:80'
    #   - '443:443'
    volumes:
      - ./ue_demo/src:/usr/share/nginx/html:ro
      #   - /usr/local/etc/ssl:/usr/local/etc/ssl
    env_file:
      - ./sample.env
